version: '3'

networks:
  default:
    external:
      name: main

services:
  terminal:
    build: .
    container_name: terminal
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 200s
      timeout: 200s
      retries: 5